models/Frames.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "frames".
 *
 * @property integer $id
 * @property string $subtype
 * @property integer $form_id
 * @property integer $frame_type_id
 * @property integer $frame_material_id
 * @property integer $frame_color_id
 * @property string $create_date
 * @property integer $goodID
 */
class Frames extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'frames';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subtype', 'form_id', 'frame_type_id', 'frame_material_id', 'frame_color_id', 'goodID'], 'required'],
            [['form_id', 'frame_type_id', 'frame_material_id', 'frame_color_id', 'goodID'], 'integer'],
            [['create_date'], 'safe'],
            [['subtype'], 'string', 'max' => 6]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subtype' => 'Subtype',
            'form_id' => 'Form ID',
            'frame_type_id' => 'Frame Type ID',
            'frame_material_id' => 'Frame Material ID',
            'frame_color_id' => 'Frame Color ID',
            'create_date' => 'Create Date',
            'goodID' => 'Good ID',
        ];
    }
    
    public function getForm(){
        return $this->hasOne(Forms::className(), ['id' => 'form_id']);
    }
    
    public function getFramematerial(){
        return $this->hasOne(Materials::className(), ['id' => 'frame_material_id']);
    }
    
    public function getFramecolor(){
        return $this->hasOne(Colors::className(), ['id' => 'frame_color_id']);
    }
}

models/Sunglasses.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "sunglasses".
 *
 * @property integer $id
 * @property string $subtype
 * @property integer $form_id
 * @property integer $frame_type_id
 * @property integer $frame_material_id
 * @property integer $lens_color_id
 * @property integer $frame_color_id
 * @property integer $lens_material_id
 * @property string $create_date
 * @property integer $goodID
 */
class Sunglasses extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sunglasses';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subtype', 'form_id', 'frame_type_id', 'frame_material_id', 'lens_color_id', 'lens_material_id', 'frame_color_id', 'goodID'], 'required'],
            [['form_id', 'frame_type_id', 'frame_material_id', 'lens_color_id', 'lens_material_id', 'frame_color_id', 'goodID'], 'integer'],
            [['create_date'], 'safe'],
            [['subtype'], 'string', 'max' => 6]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subtype' => 'Subtype',
            'form_id' => 'Form ID',
            'frame_type_id' => 'Frame Type ID',
            'frame_material_id' => 'Frame Material ID',
            'lens_color_id' => 'Lens Color ID',
            'frame_color_id' => 'Frame Color ID',
            'lens_material_id' => 'Lens Material ID',
            'create_date' => 'Create Date',
            'goodID' => 'Good ID',
        ];
    }
    
    public function getFramematerial(){
        return $this->hasOne(Materials::className(), ['id' => 'frame_material_id']);
    }
    
    public function getLensesmaterial(){
        return $this->hasOne(Materials::className(), ['id' => 'lens_material_id']);
    }
    
    public function getFramecolor(){
        return $this->hasOne(Colors::className(), ['id' => 'frame_color_id']);
    }
    
    public function getLensescolor(){
        return $this->hasOne(Colors::className(), ['id' => 'lens_color_id']);
    }
}

controllers/SunglassesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use \app\models\Goods;
use \app\models\Colors;
use \app\models\Sunglasses;
use \app\models\Brands;
use \app\models\Forms;
use \app\models\Photos;
use \app\models\Materials;
use \app\models\FramesTypes;
use \app\models\Manufacturers;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;


class SunglassesController extends Controller
{
// Заполнение тестовыми данными
    public function actionFill(){
        die;
        $brands = array_keys(ArrayHelper::map(Brands::find()->all(), 'id', 'name'));
        $forms = array_keys(ArrayHelper::map(Forms::find()->all(), 'id', 'name'));
        $frame_types = array_keys(ArrayHelper::map(FramesTypes::find()->all(), 'id', 'name'));
        $materials = array_keys(ArrayHelper::map(Materials::find()->all(), 'id', 'name'));
        $colors = array_keys(ArrayHelper::map(Colors::find()->all(), 'id', 'name'));
        $manufacturers = array_keys(ArrayHelper::map(Manufacturers::find()->all(), 'id', 'name'));
        for ($i=0;$i<500;$i++){
            $brand_id = $brands[array_rand($brands)];
            $good = new Goods();
            $good->name = "Очки ".$i;
            $good->description = "Очки Ray Ban В середине прошлого столетия, когда мода пестрила сочными фруктовыми цветами, и жизнь проходила в ритме джаза и рок-н-ролла, компания Ray-Ban покорившая мир солнечными очками ray ban aviator, завоевавшими всеобщую любовь, создала новую модель оптики, оправа которой была сделана из высококачественного пластика, - очки ray ban wayfarer. Форма стекол – дерзкая и привлекающая внимание - отражала все модные тенденции той эпохи. Сегодня миллионы людей во всем мире отдают предпочтение бренду ray ban. Очки солнцезащитные ray ban сделаны настолько универсально (и из экологически чистых материалов), что подойдут практически каждому. Купить очки ray ban несложно: достаточно зайти в наш интернет магазин, где всегда широкий ассортимент и постоянно действующие скидки. Гармоничное сочетание формы с изящными и лаконичными деталями, непревзойденное качество и стиль магнетически притягивают, и ты уже не можешь не купить ray ban. Мода меняется, но Ray Ban – бренд на все времена, выбор активных и уверенных в себе людей, любящих жизнь.";
            $good->logo = "logo1.jpg";
            $good->price = rand(1000,12000);
            $good->good_type = 1;
            $good->brand_id = $brand_id;
            $good->views_amount = rand(0,1000);
            $good->published = 1;
            $good->owner_id = 1;
            $good->ip = ip2long($_SERVER['REMOTE_ADDR']);
            $good->sku = (string)rand(10000,99999);
            $good->new = rand(0,1);
            $good->amount = rand(0,100);
            $manufacturer_id = $manufacturers[array_rand($manufacturers)];
            $good->manufacturer_id = $manufacturer_id;
            $good->rand_sort = rand(0,100000);
            if (!$good->save()){
                var_dump($good->errors);
                die;
            }
                
            
            
            $sung = new Sunglasses();
            $subtypes = ['male','female','child'];
            $subtype = $subtypes[array_rand($subtypes)];
            $sung->subtype = $subtype; // male - мужские, female - женские, child - детские
            $sung->form_id = $forms[array_rand($forms)];
            $sung->frame_type_id = $frame_types[array_rand($frame_types)];
            $sung->frame_material_id = $materials[array_rand($materials)];
            $sung->lens_color_id = $colors[array_rand($colors)];
            $sung->frame_color_id = $colors[array_rand($colors)];
            
            $sung->goodID = $good->id;
            $sung->save();
        }
        die;
        
    }

    public function actionIndex()
    {   
        $sorters_array = array();
        $sorters_array['popularity'] = 'Популярность';
        $sorters_array['brend_az'] = 'Бренд (A-Z)';
        $sorters_array['brend_za'] = 'Бренд (Z-A)';
        $sorters_array['price_inc'] = 'Цена (по возрастанию)';
        $sorters_array['price_dec'] = 'Цена (по убыванию)';
        

        Yii::$app->view->params['breadcrumbs'][] = [
            'label' => 'СОЛНЦЕЗАЩИТНЫЕ ОЧКИ',
            'template' => '<span>{link}</span>'
        ];
        $this->view->registerCssFile('resources/css/sunglasses.css');
        $this->view->registerJsFile('resources/js/jquery.json.js',['depends'=>'yii\web\JqueryAsset']);
        $this->view->registerJsFile('resources/js/optica_paginator.js',['depends'=>'yii\web\JqueryAsset']);
        $this->view->registerJsFile('resources/js/sunglasses.js',['depends'=>'yii\web\JqueryAsset']);
        
        
        $brands = Brands::find()->orderBy(['name'=> SORT_ASC])->all();
        $forms = Forms::find()->orderBy(['name'=> SORT_ASC])->all();
        $frame_types = FramesTypes::find()->orderBy(['name'=> SORT_ASC])->all();
        $frame_materials = Materials::find()
                            ->where(['id' => ArrayHelper::getColumn(ArrayHelper::toArray(Sunglasses::find()
                                                ->select('frame_material_id')
                                                ->distinct()
                                                ->orderBy(['frame_material_id'=> SORT_ASC])
                                                ->all(), 'id', 'frame_material_id'),'frame_material_id')])
                            ->orderBy(['name'=> SORT_ASC])
                            ->all();
        
        // получение всех цветов оправ, с которыми существуют очки 
        $frame_colors = Colors::find()
                            ->where(['id' => ArrayHelper::getColumn(ArrayHelper::toArray(Sunglasses::find()
                                                ->select('frame_color_id')
                                                ->distinct()
                                                ->orderBy(['frame_color_id'=> SORT_ASC])
                                                ->all(), 'id', 'frame_color_id'),'frame_color_id')])
                            ->orderBy(['name'=> SORT_ASC])
                            ->all();
        // получение всех цветов линз, с которыми существуют очки 
        $lens_colors = Colors::find()
                            ->where(['id' => ArrayHelper::getColumn(ArrayHelper::toArray(Sunglasses::find()
                                                ->select('lens_color_id')
                                                ->distinct()
                                                ->orderBy(['lens_color_id'=> SORT_ASC])
                                                ->all(), 'id', 'lens_color_id'),'lens_color_id')])
                            ->orderBy(['name'=> SORT_ASC])
                            ->all();
        
        
        
        return $this->render('index', [
            'sorter_by_array' => $sorters_array,
            'brands' => $brands,
            'forms' => $forms,
            'frame_types' => $frame_types,
            'frame_materials' => $frame_materials,
            'lens_colors' => $lens_colors,
            'frame_colors' => $frame_colors
        ]);
    }

    // Получение списка
    public function actionGetlist(){
        $sunglasses = Goods::find()
                ->leftJoin('brands b', 'brand_id=b.id')
                ->leftJoin('sunglasses sng', 'goods.id=sng.goodID');
        $where = array('published' => 1);
        $where['good_type'] = 1;
        $sunglasses->where($where);
        
        
        if (!empty($_REQUEST['new']))
            $sunglasses->andWhere('`new`=1');
        
        // цена от
        if (!empty($_REQUEST['price_from']))
            $sunglasses->andWhere('`price`>:price_from', [':price_from'=>$_REQUEST['price_from']]);
        
        // цена до
        if (!empty($_REQUEST['price_to']))
            $sunglasses->andWhere('`price`<:price_to', [':price_to'=>$_REQUEST['price_to']]);
        
        // бренды
        if (!empty($_REQUEST['brands'])){
            $brands_ids = json_decode($_REQUEST['brands']);
            sort($brands_ids);
            $sunglasses->andWhere(['brand_id' => $brands_ids]);
        }
        
        // формы
        if (!empty($_REQUEST['forms'])){
            $forms_ids = json_decode($_REQUEST['forms']);
            sort($forms_ids);
            $sunglasses->andWhere(['sng.form_id' => $forms_ids]);
        }
        
        // типы оправ
        if (!empty($_REQUEST['frames'])){
            $frames_ids = json_decode($_REQUEST['frames']);
            sort($frames_ids);
            $sunglasses->andWhere(['sng.frame_type_id' => $frames_ids]);
        }
        
        // материалы оправ
        if (!empty($_REQUEST['materials'])){
            $materials_ids = json_decode($_REQUEST['materials']);
            sort($materials_ids);
            $sunglasses->andWhere(['sng.frame_material_id' => $materials_ids]);
        }
        
        // по полу
        if (!empty($_REQUEST['subtypes'])){
            $subtype_ids = json_decode($_REQUEST['subtypes']);
            sort($subtype_ids);
            $sunglasses->andWhere(['sng.subtype' => $subtype_ids]);
        }
        
        
        // по цвету линз
        if (!empty($_REQUEST['lens_color_id'])){
            $sunglasses->andWhere(['sng.lens_color_id' => (int)$_REQUEST['lens_color_id']]);
        /*    $ids_arr = ArrayHelper::getColumn(ArrayHelper::toArray(Sunglasses::find()
                                                ->select('goodID')
                                                ->distinct()
                                                ->andWhere('`lens_color_id`=:lens_color_id', [':lens_color_id'=>$_REQUEST['lens_color_id']])
                                                ->all(), 'id', 'goodID'),'goodID');
            $sunglasses->andWhere(['goods.id' => $ids_arr]);*/
        }
        
        // по цвету оправы
        if (!empty($_REQUEST['frame_color_id'])){

views/sunglasses/index.php
<?php use yii\widgets\Breadcrumbs; ?>
<?php echo \Yii::$app->view->renderFile('@app/views/site/slider.php'); ?>
<div class="sunglasses-page"> 
    <div class="search-params">
        <div class="title">ПАРАМЕТРЫ ПОИСКА</div>
        <div class="btn new-filters" id="new-filters">НОВИНКИ</div>
        <div class="optica_select price-filter" id="price-filter">
            <div class="header">
                <div class="text">
                    ЦЕНА, руб
                </div>
                <div class="arrow-place">
                    <img src="./resources/img/arrow-down.png">
                </div>
            </div>
            <div class="list">
                <div data-min="0" data-max="3000" data-value="-3">до 3000</div>
                <div data-min="3000" data-max="6000" data-value="3-6">от 3000 до 6000</div>
                <div data-min="6000" data-max="9000" data-value="6-9">от 6000 до 9000</div>
                <div data-min="9000" data-max="12000" data-value="9-12">от 9000 до 12000</div>
                <div data-min="12000" data-max="15000" data-value="12-15">от 12000 до 15000</div>
            </div>
        </div>
        <div class="search-title">БРЕНДЫ</div>
        <div class="optica_select_panel brands-filter" id="brands-filter">
            <?php foreach ($brands as $number => $brand): ?>
            <div data-value="<?=$brand->id;?>"><?=$brand->name;?></div>
            <?php endforeach; ?>
        </div>
        <div class="search-title">ФОРМА</div>
        <div class="optica_select_panel forms-filter" id="forms-filter">
            <?php foreach ($forms as $number => $form): ?>
            <div data-value="<?=$form->id;?>"><img src="./resources/img/<?=$form->img_url;?>"><span><?=$form->name;?></span></div>
            <?php endforeach; ?>
        </div>
        <div class="search-title">ТИП ОПРАВЫ</div>
        <div class="optica_select_panel frame-filter" id="frame-filter">
            <?php foreach ($frame_types as $number => $frame_type): ?>
            <div data-value="<?=$frame_type->id;?>"><img src="./resources/img/<?=$frame_type->img_url;?>"><span><?=$frame_type->name;?></span></div>
            <?php endforeach; ?>
        </div>
        <div class="search-title">МАТЕРИАЛ ОПРАВЫ</div>
        <div class="optica_select_panel material-filter" id="material-filter">
            <?php foreach ($frame_materials as $number => $frame_material): ?>
            <div data-value="<?=$frame_material->id;?>"><?=$frame_material->name;?></div>
            <?php endforeach; ?>
        </div>
        <div class="search-title">ЦВЕТ ОПРАВЫ</div>
        <div class="optica_select frame-color-filter" id="frame-color-filter">
            <div class="header">
                <div class="text">
                    выберите цвет
                </div>
                <div class="arrow-place">
                    <img src="./resources/img/arrow-down.png">
                </div>
            </div>
            <div class="list">
                <?php foreach ($frame_colors as $number => $frame_color): ?>
                <div data-value="<?=$frame_color->id;?>"><?=$frame_color->name;?></div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="search-title">ЦВЕТ ЛИНЗ</div>
        <div class="optica_select lens-color-filter" id="lens-color-filter">
            <div class="header">
                <div class="text">
                    выберите цвет
                </div>
                <div class="arrow-place">
                    <img src="./resources/img/arrow-down.png">
                </div>
            </div>
            <div class="list">
                <?php foreach ($lens_colors as $number => $lens_color): ?>
                <div data-value="<?=$lens_color->id;?>"><?=$lens_color->name;?></div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="btn clear-filters" id="clear-filters">СБРОСИТЬ</div>
    </div>
    <div class="sunglasses-place">
        <?php echo Breadcrumbs::widget([
                'homeLink' => [ 
                    'label' => 'ГЛАВНАЯ',
                    'url' => Yii::$app->homeUrl,
                    'template' => "<span>{link}</span> - ", // template for this link only
                ],
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]); ?>
        <div class="title">СОЛНЦЕЗАЩИТНЫЕ ОЧКИ</div>
        <div class="filters">    
            <div class="buttons-group subtype-buttons">
                <div class="col col-1">
                    <div data-value="male" id="male" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'male')==0)?' pressed':'';?>">МУЖСКИЕ</div>
                </div>
                <div class="col col-2">
                    <div data-value="female" id="female" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'female')==0)?' pressed':'';?>">ЖЕНСКИЕ</div>
                </div>
                <div class="col col-3">
                    <div data-value="child" id="child" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'child')==0)?' pressed':'';?>">ДЕТСКИЕ</div>
                </div>
            </div>
            <div class="sortby-and-paging">
                <div class="sortby">
                    <span>Отсортировать по</span>
                    <div class="optica_select sortby-filter" id="sortby-filter">
                        <div class="header">
                            <div class="text">
                                ЦЕНА
                            </div>
                            <div class="arrow-place">
                                <img src="./resources/img/arrow-down.png">
                            </div>
                        </div>
                        <div class="list">
                            <?php
                                $first = true;
                                foreach($sorter_by_array AS $key => $sort_param): ?>
                                    <div <?php if ($first) echo 'class="selected" '; $first=false;?>data-value="<?=$key; ?>"><?=$sort_param; ?></div>
                                <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="optica_paginator">
                    <span class="home">начало</span>
                    <span class="prev">пред.</span>
                    <span class="numbers"></span>
                    <span class="next">след.</span>
                    <span class="end">конец</span>
                </div>
            </div>
        </div>
        <div class="content">
            
        </div>
        <div class="optica_paginator bottom">
            <span class="home">начало</span>
            <span class="prev">пред.</span> 
            <span class="numbers"></span>
            <span class="next">след.</span>
            <span class="end">конец</span>
        </div>
    </div>
</div>

views/sunglasses/list.php
<?php
use yii\i18n\Formatter;
$column_counter = 1;
if (count($sunglasses)>0){
    $cart_arr = array();
    if (!empty($_COOKIE['cart'])){
        $cart_arr = json_decode($_COOKIE['cart'], true);
    }
  /*  var_dump($cart_arr );
    die;*/
    foreach ($sunglasses as $number => $item): ?>
        <div class="col col-<?=$column_counter; ?>">
            <div class="item" data-id="<?=$item->id;?>">
                <div class="name"><?=$item->brand->name;?> <?=$item->name;?></div>
                <div class="logo">
                    <img src="/images/<?=$item->logo;?>">
                </div>
                <div class="bottom">
                    <div class="price"><?=$item->price;?> руб.</div>
                    <?php 
                    $incart = false;
                    if (in_array($item->id, $cart_arr))
                        $incart = true;
                    ?>
                    <img title="Добавить в корзину" <?php if ($incart): ?>style="display: none;"<?php endif; ?> data-id="<?=$item->id;?>" class="basket" src="/resources/img/basket.png">
                    <a title="Перейти в корзину" <?php if (!$incart): ?>style="display: none;"<?php endif; ?> class="in_cart" href="/cart">В корзине</a>
                </div>
            </div>
        </div>
    <?php
    $column_counter == 3?$column_counter = 1:$column_counter++;
    endforeach;
} else {
    ?>
    <h2 class="no-goods-message">К сожалению, по Вашему запросу товаров не найдено</h2>
    <?php
}
?> 

views/sunglasses/product.php
<?php use yii\widgets\Breadcrumbs; ?>
<?php echo Breadcrumbs::widget([
    'homeLink' => [ 
        'label' => 'ГЛАВНАЯ',
        'url' => Yii::$app->homeUrl,
        'template' => "<span>{link}</span> - ",
    ],
    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
]); ?>

<div class="item">
    <div class="name_place">
        <div class="name"><?=$product->name; ?></div>
        <div class="views">
            <span><?=$product->views_amount; ?></span>
            <img class="attach-file-image" src="/resources/img/eye.png">
        </div>
    </div>
    <div class="info">
        <div class="left">
            <div class="photos">
                <?php if (!empty($photos)): ?>
                <div class="main">
                    <img src="/images/<?=$photos[0]->photo_name; ?>">
                </div>
                <?php if (count($photos)>1): ?>
                <div class="another">
                    <?php foreach ($photos as $number => $photo): ?> 
                            <div class="col-<?=($number+1);?>">
                                <img src="/images/<?=$photo->photo_name;?>">
                            </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="social">
              <div class="pluso" data-background="transparent" data-options="medium,round,line,horizontal,nocounter,theme=04" data-services="google,twitter,vkontakte,facebook,moimir,odnoklassniki"></div>
            </div>
            <div class="back">
                <a href="/sunglasses"><img src="/resources/img/arrow-back.png">
                    Вернуться к списку товаров</a>
            </div>
            <div></div>
        </div>
        <div class="right">
            <div class="main">
                <div class="brand_name param">
                    <div class="label">Бренд:</div>
                    <div class="value"><?=$product->brand->name; ?></div>
                </div>
                <div class="sku param">
                    <div class="label">Код модели:</div>
                    <div class="value"><?=$product->sku; ?></div>
                </div>
                <div class="manufacturer param">
                    <div class="label">Производитель:</div>
                    <div class="value"><?=$product->manufacturer->name; ?></div>
                </div>
                <div class="material param">
                    <div class="label">Материал оправы:</div>
                    <div class="value"><?=$product->sunglasses->framematerial->name; ?></div>
                </div>
                <div class="frame-color param">
                    <div class="label">Цвет оправы:</div>
                    <div class="value"><?=$product->sunglasses->framecolor->name; ?></div>
                </div>
                <div class="lenses-color param">
                    <div class="label">Материал линз:</div>
                    <div class="value"><?=$product->sunglasses->lensesmaterial->name; ?></div>
                </div>
                <div class="lenses-color param">
                    <div class="label">Цвет линз:</div>
                    <div class="value"><?=$product->sunglasses->lensescolor->name; ?></div>
                </div>
                <div class="sex param">
                    <div class="label">Пол:</div>
                    <div class="value"><?=$subtype; ?></div>
                </div>
            </div>
            <div class="price"><div class="text">ЦЕНА</div><div class="value"><?=$product->price; ?> руб.</div></div>
            <div id="add-to-basket" data-id="<?=$product->id; ?>">КУПИТЬ СЕЙЧАС</div>
        </div>
    </div>
</div>
<?php if (!empty($similar)): ?>
    <div class="similar">
        <div class="head">ПОХОЖИЕ ТОВАРЫ</div>
        <div class="body">
            <?php
                $column_counter = 1;
                foreach ($similar as $number => $good): ?> 
                    <div class="col col-<?=($column_counter);?>">
                        <div class="similar-item" data-id="<?=$good->id;?>" data-type="<?=$good->good_type;?>">
                            
                            <div class="logo">
                                <img src="/images/<?=$good->logo;?>">
                            </div>
                            <div class="name">
                                <?=$good->name;?>
                            </div>
                            <div class="price">
                                Цена <span><?=$good->price;?> руб</span>
                            </div>
                        </div>
                        
                    </div>
                <?php
                    if ($column_counter == 6){
                        $column_counter = 1;
                    } else {
                        $column_counter++;
                    }
                ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!empty($history)): ?>
    <div class="history">
        <div class="head">ВЫ СМОТРЕЛИ</div>
        <div class="body">
            <?php
                $column_counter = 1;
                foreach ($history as $number => $good): ?> 
                    <div class="col col-<?=($column_counter);?>">
                        <div class="history-item" data-id="<?=$good->id;?>" data-type="<?=$good->good_type;?>">
                            
                            <div class="logo">
                                <img src="/images/<?=$good->logo;?>">
                            </div>
                            <div class="name">
                                <?=$good->name;?>
                            </div>
                            <div class="price">
                                Цена <span><?=$good->price;?> руб</span>
                            </div>
                        </div>
                        
                    </div>
                <?php
                    if ($column_counter == 6){
                        $column_counter = 1;
                    } else {
                        $column_counter++;
                    }
                ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>