models/Goods.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "goods".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $logo
 * @property string $price
 * @property integer $good_type
 * @property integer $brand_id
 * @property integer $views_amount
 * @property integer $published
 * @property integer $amount
 * @property integer $owner_id
 * @property string $create_date
 * @property integer $ip
 * @property string $sku
 * @property integer $new
 * @property integer $manufacturer_id
 * @property integer $rand_sort
 */
class Goods extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'goods';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'price', 'good_type', 'brand_id', 'amount', 'owner_id', 'ip', 'sku', 'new', 'manufacturer_id', 'rand_sort'], 'required'],
            [['description', 'logo', 'sku'], 'string'],
            [['price'], 'number'],
            [['good_type', 'brand_id', 'views_amount', 'published', 'amount', 'owner_id', 'ip', 'new', 'manufacturer_id', 'rand_sort'], 'integer'],
            [['create_date'], 'safe'],
            [['name'], 'string', 'max' => 150]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'logo' => 'Logo',
            'price' => 'Price',
            'good_type' => 'Good Type',
            'brand_id' => 'Brand ID',
            'views_amount' => 'Views Amount',
            'published' => 'Published',
            'amount' => 'Amount',
            'owner_id' => 'Owner ID',
            'create_date' => 'Create Date',
            'ip' => 'Ip',
            'sku' => 'Sku',
            'new' => 'New',
            'manufacturer_id' => 'Manufacturer ID',
            'rand_sort' => 'Rand Sort',
        ];
    }
    
    // Добавление товара в историю просмотров
    static function toHistory($id){
        $history_arr = array();
        if (!empty($_COOKIE['history'])){
            $history_arr = json_decode($_COOKIE['history'], true);
            if (!in_array($id, $history_arr)){
                array_unshift($history_arr, $id); // Вставка в начало
                if (count($history_arr)>6)
                    array_pop($history_arr); // Удаление последнего
            } else {
                $key = array_search($id, $history_arr);
                unset($history_arr[$key]);
                sort($history_arr);
                array_unshift($history_arr, $id); 
            }
        } else {
            $history_arr[] = $id;
        }
        $history_json = json_encode($history_arr);
        setcookie('history', $history_json, -1, '/');
    }
    
    static function getHistory(){
        $history_arr = array();
        if (!empty($_COOKIE['history']))
            $history_arr = json_decode($_COOKIE['history'], true);
        return $history_arr;
    }
    
    public function getBrand(){
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }
    
    public function getManufacturer(){
        return $this->hasOne(Manufacturers::className(), ['id' => 'manufacturer_id']);
    }
    
    public function getSunglasses(){
        return $this->hasOne(Sunglasses::className(), ['goodID'=>'id']);
    }
    
    public function getFrames(){
        return $this->hasOne(Frames::className(), ['goodID' => 'id']);
    }
    
    public function getLenses(){
        return $this->hasOne(Lenses::className(), ['goodID' => 'id']);
    }
    
    public function getRelated(){
        return $this->hasOne(Related::className(), ['goodID'=>'id']);
    }
}

models/Related.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "related".
 *
 * @property integer $id
 * @property string $subtype
 * @property integer $capacity
 * @property string $country
 * @property string $create_date
 * @property integer $goodID
 */
class Related extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'related';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subtype', 'goodID'], 'required'],
            [['capacity', 'goodID'], 'integer'],
            [['country'], 'string'],
            [['create_date'], 'safe'],
            [['subtype'], 'string', 'max' => 8]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subtype' => 'Subtype',
            'capacity' => 'Capacity',
            'country' => 'Country',
            'create_date' => 'Create Date',
            'goodID' => 'Good ID',
        ];
    }
}

controllers/RelatedController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use \app\models\Goods;
use \app\models\Brands;
use \app\models\Photos;
use \app\models\Related;
use \app\models\Manufacturers;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;


class RelatedController extends Controller
{
    // Заполнение тестовыми данными
    public function actionFill(){
        $brands = array_keys(ArrayHelper::map(Brands::find()->all(), 'id', 'name'));
        $manufacturers = array_keys(ArrayHelper::map(Manufacturers::find()->all(), 'id', 'name'));
        $materials = array_keys(ArrayHelper::map(Materials::find()->all(), 'id', 'name'));
        for ($i=0;$i<500;$i++){
            $brand_id = $brands[array_rand($brands)];
            $good = new Goods();
            $subtypes = ['solution','drops','set','case','napkin','spray'];
            $subtype = $subtypes[array_rand($subtypes)];
            $name = "Раствор ";
            switch($subtype){
                case 'solution':
                    $name = "Раствор ";
                    break;
                case 'drops':
                    $name = "Увлажняющие капли ";
                    break;
                case 'set':
                    $name = "Набор для линз ";
                    break;
                case 'case':
                    $name = "Футляр ";
                    break;
                case 'napkin':
                    $name = "Салфетки ";
                    break;
                case 'spray':
                    $name = "Спрей ";
                    break;
            }
            $good->name = $name.$i;
            $good->description = "Модуль Сопутствующие товары позволяет Вашим клиентам обратить внимание, а то и прикупить заодно с выбранным товаром, сопутствующий ему.
Например, в вашем магазине имеются в продаже удочки, катушки, леска и прочие снасти. К категории \"Удочки\" довольно уместно привязать категории \"Леска\", \"Катушки\", - в таком случае, пользователь находясь в карточке товара выбранного заветного удилища будет видеть блок сопутствующий товаров(аксессуаров), что непременно повлечет к покупке \"крючка и лески\" к удочке. Или же у Вас в продаже Фотокамеры, - обязательно нужно предложить к фотокамере приобрести объектив, сумку-чехол, карту памяти и т.д.";
            $logo = "solution.jpg";
            switch($subtype){
                case 'solution':
                    $logo = "solution.jpg";
                    break;
                case 'drops':
                    $logo = "drops.jpg";
                    break;
                case 'set':
                    $logo = "set.jpg";
                    break;
                case 'case':
                    $logo = "case.jpg";
                    break;
                case 'napkin':
                    $logo = "napkin.jpg";
                    break;
                case 'spray':
                    $logo = "spray.jpg";
                    break;
            }
            $good->logo = $logo;
            $good->price = rand(100,3000);
            $good->good_type = 4;
            $good->brand_id = $brand_id;
            $good->views_amount = rand(0,1000);
            $good->published = 1;
            $good->owner_id = 1;
            $good->ip = ip2long($_SERVER['REMOTE_ADDR']);
            $good->sku = (string)rand(10000,99999);
            $good->new = rand(0,1);
            $manufacturer_id = $manufacturers[array_rand($manufacturers)];
            $good->manufacturer_id = $manufacturer_id;
            $good->amount = rand(0,100);
            $good->rand_sort = rand(0,100000);
            if (!$good->save()){
                var_dump($good->errors);
                die;
            }
            
            $photo = new Photos();
            $photo->photo_name = $logo;
            $photo->good_id = $good->id;
            if (!$photo->save()){
                var_dump($photo->errors);
                die;
            }
            
            $rel = new Related();
            $rel->subtype = $subtype;
            if (in_array($subtype, array('solution', 'spray', 'napkin', 'drops'))){
                $rel->capacity = rand(10,100);
            } else {
                $rel->country = "Россия";
            }
            
            $rel->goodID = $good->id;
            if (!$rel->save()){
                var_dump($rel->errors);
                die;
            }
        }
        die;
    }
    
    public function actionIndex()
    {   
        $sorters_array = array();
        $sorters_array['popularity'] = 'Популярность';
        $sorters_array['brend_az'] = 'Бренд (A-Z)';
        $sorters_array['brend_za'] = 'Бренд (Z-A)';
        $sorters_array['price_inc'] = 'Цена (по возрастанию)';
        $sorters_array['price_dec'] = 'Цена (по убыванию)';
        Yii::$app->view->params['breadcrumbs'][] = [
            'label' => 'СОПУТСТВУЮЩИЕ ТОВАРЫ',
            'template' => '<span>{link}</span>'
        ];
        $this->view->registerCssFile('resources/css/related.css');
        $this->view->registerJsFile('resources/js/jquery.json.js',['depends'=>'yii\web\JqueryAsset']);
        $this->view->registerJsFile('resources/js/optica_paginator.js',['depends'=>'yii\web\JqueryAsset']);
        $this->view->registerJsFile('resources/js/related.js',['depends'=>'yii\web\JqueryAsset']);
        $manufacturers = Manufacturers::find()->orderBy(['name'=> SORT_ASC])->all();
        return $this->render('index', [
            'manufacturers' => $manufacturers,
            'sorter_by_array' => $sorters_array
        ]);
    }
    // Получение списка
    public function actionGetlist(){
        $related = Goods::find()
           ->leftJoin('brands b', 'brand_id=b.id')
            ->leftJoin('related rltd', 'goods.id=rltd.goodID');
        $where = array('published' => 1);
        $where['good_type'] = 4;
        $related->where($where);

        
        if (!empty($_REQUEST['new']))
            $related->andWhere('`new`=1');
        
        // цена от
        if (!empty($_REQUEST['price_from']))
            $related->andWhere('`price`>:price_from', [':price_from'=>$_REQUEST['price_from']]);

        // цена до
        if (!empty($_REQUEST['price_to']))
            $related->andWhere('`price`<:price_to', [':price_to'=>$_REQUEST['price_to']]);

        // производители
        if (!empty($_REQUEST['manufacturers'])){
            $manufacturers_ids = json_decode($_REQUEST['manufacturers']);
            sort($manufacturers_ids);
            $related->andWhere(['manufacturer_id' => $manufacturers_ids]);
        }

        if (!empty($_REQUEST['subtypes'])){
            $subtypes = json_decode($_REQUEST['subtypes']);
            sort($subtypes);
            $related->andWhere(['rltd.subtype' => $subtypes]);
        }

        // сортировка
        if (empty($_REQUEST['sortby']) || strcmp($_REQUEST['sortby'],'popularity')==0)
            $related->orderBy(['views_amount'=> SORT_DESC]);
        else {
            switch($_REQUEST['sortby']){
                case 'brend_az':
                    $related->orderBy(['b.name'=> SORT_ASC]);
                    break;
                case 'brend_za':
                    $related->orderBy(['b.name'=> SORT_DESC]);
                    break;
                case 'price_inc':
                    $related->orderBy(['price'=> SORT_ASC]);
                    break;
                case 'price_dec':
                    $related->orderBy(['price'=> SORT_DESC]);
                    break;
            }
        }
        $countQuery = clone $related;
        $totalCount = $countQuery->count();
        $models = $related->offset(($_REQUEST['page']-1)*30)
            ->limit(30)
            ->all();
        echo json_encode(array(
            'html'=>$this->renderAjax('list',array(
                    'related' => $models  
                )
            ),
            'count' => $totalCount
        ));
    }
    
    // Карточка товара
    public function actionProduct(){
        if (empty($_GET['id']))
            throw new HttpException(404, 'Not Found');
        else {
            $product = Goods::find()
                ->where(['published' => 1,'good_type' => 4, 'goods.id' => (int)$_GET['id']])
                ->one();
            if (empty($product))
                throw new HttpException(404, 'Product Does Not Exist');
            $product->views_amount++; // Увеличение количества просмотров
            $product->save();
            $history_ids = Goods::getHistory(); // Получение списка просмотренных товаров
            $history = Goods::find()
                    ->where(['id' => $history_ids, 'published' => 1])
                    ->all();

            Goods::toHistory($_GET['id']); // Добавление в историю просмотров


            
            // Формирование "Хлебных крошек"
            Yii::$app->view->params['breadcrumbs'][] = [
                'label' => "СОПУТСТВУЮЩИЕ ТОВАРЫ",
                'url' => '/related',
                'template' => '<span>{link}</span> - '
            ];
            
            Yii::$app->view->params['breadcrumbs'][] = [
                'label' => mb_strtoupper($product->name, "utf-8"),
                'template' => '<span>{link}</span>'
            ];
            // Получение фотографий товара
            $photos = Photos::find()
                    ->where(['good_id' => (int)$_GET['id']])
                    ->offset(0)
                    ->limit(4)
                    ->all();
            $this->view->registerCssFile('/resources/css/similar.css');
            $this->view->registerCssFile('/resources/css/history.css');
            $this->view->registerCssFile('/resources/css/related_product.css');
            $this->view->registerJsFile('/resources/js/related_product.js',['depends'=>'yii\web\JqueryAsset']);

            // Похожие товары
            $similar = Goods::find()
                ->where(['published' => 1,'good_type' => 4, 'goods.sku' => $product->sku])

views/related/index.php
<?php use yii\widgets\Breadcrumbs; ?>
<?php echo \Yii::$app->view->renderFile('@app/views/site/slider.php'); ?>
<div class="related-page"> 
    <div class="search-params">
        <div class="title">ПАРАМЕТРЫ ПОИСКА</div>
        <div class="btn new-filters" id="new-filters">НОВИНКИ</div>
        <div class="optica_select_slider price-filter" id="price-filter">
            <div class="header">
                <div class="text">
                    ЦЕНА, руб
                </div>
                <div class="arrow-place">
                    <img class="arrow" src="./resources/img/arrow-down.png">
                </div>
            </div>
            <div class="slider-place">
                <div class="slider"></div>
                <div class="from">500 руб</div>
                <div class="to">2000 руб</div>
            </div>
        </div>
        <div class="search-title">ПРОИЗВОДИТЕЛЬ</div>
        <div class="optica_select_panel manufacturers-filter" id="manufacturers-filter">
            <?php foreach ($manufacturers as $number => $manufacturer): ?>
            <div data-value="<?=$manufacturer->id;?>"><?=$manufacturer->name;?></div>
            <?php endforeach; ?>
        </div>
        <div class="btn clear-filters" id="clear-filters">СБРОСИТЬ</div>
    </div>
    <div class="related-place">
        <?php echo Breadcrumbs::widget([
                'homeLink' => [ 
                    'label' => 'ГЛАВНАЯ',
                    'url' => Yii::$app->homeUrl,
                    'template' => "<span>{link}</span> - ", // template for this link only
                ],
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]); ?>
        <div class="title">СОПУТСТВУЮЩИЕ ТОВАРЫ</div>
        <div class="filters">
            <div class="buttons-group subtype-buttons">
                <div class="col col-1">
                    <div data-value="solution" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'solution')==0)?' pressed':'';?>">РАСТВОРЫ</div>
                </div>
                <div class="col col-2">
                    <div data-value="drops" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'drops')==0)?' pressed':'';?>">УВЛАЖНЯЮЩИЕ КАПЛИ</div>
                </div>
                <div class="col col-3">
                    <div data-value="set" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'set')==0)?' pressed':'';?>">НАБОРЫ ДЛЯ ЛИНЗ</div>
                </div>
                <div class="col col-1">
                    <div data-value="case" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'case')==0)?' pressed':'';?>">ФУТЛЯРЫ</div>
                </div>
                <div class="col col-2">
                    <div data-value="napkin" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'napkin')==0)?' pressed':'';?>">САЛФЕТКИ</div>
                </div>
                <div class="col col-3">
                    <div data-value="spray" class="btn<?=(isset($_GET['subtype'])&&strcmp($_GET['subtype'],'spray')==0)?' pressed':'';?>">СПРЕИ</div>
                </div>
            </div>

            <div class="sortby-and-paging">
                <div class="sortby">
                    <span>Отсортировать по</span>
                    <div class="optica_select sortby-filter" id="sortby-filter">
                        <div class="header">
                            <div class="text">
                                ЦЕНА
                            </div>
                            <div class="arrow-place">
                                <img src="./resources/img/arrow-down.png">
                            </div>
                        </div>
                        <div class="list">
                            <?php
                                $first = true;
                                foreach($sorter_by_array AS $key => $sort_param): ?>
                                    <div <?php if ($first) echo 'class="selected" '; $first=false;?>data-value="<?=$key; ?>"><?=$sort_param; ?></div>
                                <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="optica_paginator">
                    <span class="home">начало</span>
                    <span class="prev">пред.</span>
                    <span class="numbers"></span>
                    <span class="next">след.</span>
                    <span class="end">конец</span>
                </div>
            </div>
        </div>
        <div class="content">
            
        </div>
        <div class="optica_paginator bottom">
            <span class="home">начало</span>
            <span class="prev">пред.</span> 
            <span class="numbers"></span>
            <span class="next">след.</span>
            <span class="end">конец</span>
        </div>
    </div>
</div>

views/related/list.php
<?php
$column_counter = 1;
if (count($related)>0){
    $cart_arr = array();
    if (!empty($_COOKIE['cart'])){
        $cart_arr = json_decode($_COOKIE['cart'], true);
    }
    foreach ($related as $number => $item): ?>
        <div class="col col-<?=$column_counter; ?>">
            <div class="item" data-id="<?=$item->id;?>">
                <div class="name"><?=$item->brand->name;?> <?=$item->name;?></div>
                <div class="logo">
                    <img src="/images/<?=$item->logo;?>">
                </div>
                <div class="bottom">
                    <div class="price"><?=$item->price;?> руб.</div>
                    <?php 
                    $incart = false;
                    if (in_array($item->id, $cart_arr))
                        $incart = true;
                    ?>
                    <img title="Добавить в корзину" <?php if ($incart): ?>style="display: none;"<?php endif; ?> data-id="<?=$item->id;?>" class="basket" src="/resources/img/basket.png">
                    <a title="Перейти в корзину" <?php if (!$incart): ?>style="display: none;"<?php endif; ?> class="in_cart" href="/cart">В корзине</a>
                </div>
            </div>
        </div>
    <?php
    $column_counter == 3?$column_counter = 1:$column_counter++;
    endforeach;
} else {
    ?>
    <h2 class="no-goods-message">К сожалению, по Вашему запросу товаров не найдено</h2>
    <?php
}
?> 

views/related/product.php
<?php use yii\widgets\Breadcrumbs; ?>
<?php echo Breadcrumbs::widget([
    'homeLink' => [ 
        'label' => 'ГЛАВНАЯ',
        'url' => Yii::$app->homeUrl,
        'template' => "<span>{link}</span> - ",
    ],
    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
]); ?>

<div class="item">
    <div class="name_place">
        <div class="name"><?=$product->name; ?></div>
        <div class="views">
            <span><?=$product->views_amount; ?></span>
            <img class="attach-file-image" src="/resources/img/eye.png">
        </div>
    </div>
    <div class="info">
        <div class="left">
            <div class="photos">
                <?php if (!empty($photos)): ?>
                <div class="main">
                    <img src="/images/<?=$photos[0]->photo_name; ?>">
                </div>
                <?php if (count($photos)>1): ?>
                <div class="another">
                    <?php foreach ($photos as $number => $photo): ?> 
                            <div class="col-<?=($number+1);?>">
                                <img src="/images/<?=$photo->photo_name;?>">
                            </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="social">
              <div class="pluso" data-background="transparent" data-options="medium,round,line,horizontal,nocounter,theme=04" data-services="google,twitter,vkontakte,facebook,moimir,odnoklassniki"></div>
            </div>
            <div class="back">
                <a href="/related"><img src="/resources/img/arrow-back.png">
                    Вернуться к списку товаров</a>
            </div>
            <div></div>
        </div>
        <div class="right">
            <div class="main">
                <?php if (in_array($product->related->subtype, array('solution', 'spray', 'napkin', 'drops'))): ?>
                <div class="capacity param">
                    <div class="label">Объем:</div>
                    <div class="value">
                    <?php if (!empty($product->related->capacity)): ?>    
                        <?=$product->related->capacity; ?> мл
                    <?php else: ?>
                        -
                    <?php endif; ?>
                    </div>
                </div>
                <div class="manufacturer param">
                    <div class="label">Производитель:</div>
                    <div class="value"><?=$product->manufacturer->name; ?></div>
                </div>
                <?php else: ?>
                <div class="country param">
                    <div class="label">Страна производства:</div>
                    <div class="value"><?=$product->related->country; ?></div>
                </div>
                <?php endif; ?>
            </div>
            <div class="price"><div class="text">ЦЕНА</div><div class="value"><?=$product->price; ?> руб.</div></div>
            <div id="add-to-basket" data-id="<?=$product->id; ?>">КУПИТЬ СЕЙЧАС</div>
        </div>
    </div>
</div>
<?php if (!empty($similar)): ?>
    <div class="similar">
        <div class="head">ПОХОЖИЕ ТОВАРЫ</div>
        <div class="body">
            <?php
                $column_counter = 1;
                foreach ($similar as $number => $good): ?> 
                    <div class="col col-<?=($column_counter);?>">
                        <div class="similar-item" data-id="<?=$good->id;?>" data-type="<?=$good->good_type;?>">
                            
                            <div class="logo">
                                <img src="/images/<?=$good->logo;?>">
                            </div>
                            <div class="name">
                                <?=$good->name;?>
                            </div>
                            <div class="price">
                                Цена <span><?=$good->price;?> руб</span>
                            </div>
                        </div>
                        
                    </div>
                <?php
                    if ($column_counter == 6){
                        $column_counter = 1;
                    } else {
                        $column_counter++;
                    }
                ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!empty($history)): ?>
    <div class="history">
        <div class="head">ВЫ СМОТРЕЛИ</div>
        <div class="body">
            <?php
                $column_counter = 1;
                foreach ($history as $number => $good): ?> 
                    <div class="col col-<?=($column_counter);?>">
                        <div class="history-item" data-id="<?=$good->id;?>" data-type="<?=$good->good_type;?>">
                            
                            <div class="logo">
                                <img src="/images/<?=$good->logo;?>">
                            </div>
                            <div class="name">
                                <?=$good->name;?>
                            </div>
                            <div class="price">
                                Цена <span><?=$good->price;?> руб</span>
                            </div>
                        </div>
                        
                    </div>
                <?php
                    if ($column_counter == 6){
                        $column_counter = 1;
                    } else {
                        $column_counter++;
                    }
                ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>